server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imdb-db-user
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    propeties:
      hibernate:
        show_sql: true

springdoc:
  swagger-ui:
    path: /documentacao-api
  api-docs:
    path: /api-docs